### ISSUE TITLE
VMSS Extension Failure: Incompatibility with Python 3.8+ in Microsoft.VisualStudio.Services.TeamServicesAgentLinux on Ubuntu 24.04

### ISSUE THREAD

**Issue by jared-jakacky-kdi** [actions/virtual-environments#10798]
### Description

The Azure DevOps agent extension Microsoft.VisualStudio.Services.TeamServicesAgentLinux fails during installation on a Virtual Machine Scale Set (VMSS) running Ubuntu 24.04 images from the runner-images repository. The terminal error occurs due to an incompatibility with the Python environment on the VM, specifically because the extension relies on the imp.load_source function, which was deprecated in Python 3.4 and removed in Python 3.7. When the VMSS is running a newer version of Python (3.8 or higher), this function is no longer available, causing the extension's handler script to fail during execution.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Ubuntu2404

### Is it regression?

Yes, Ubuntu 22.04 still supports 3.7.*

### Expected behavior

The extension should install and run successfully on the Virtual Machine Scale Set without errors.

### Actual behavior

Startup fails with the following error

`The handler for VM extension type 'Microsoft.VisualStudio.Services.TeamServicesAgentLinux' has reported terminal failure for VM extension 'Microsoft.Azure.DevOps.Pipelines.Agent' with error message: '[ExtensionOperationError] Non-zero exit code: 1, /var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/Handler.sh [stdout] [stderr] Traceback (most recent call last): File "/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/Utils/WAAgentUtil.py", line 57, in <module> waagent = imp.load_source('waagent', agentPath) ^^^^^^^^^^^^^^^ AttributeError: module 'importlib' has no attribute 'load_source' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/./AzureRM.py", line 9, in <module> import Utils.HandlerUtil as Util File "/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/Utils/HandlerUtil.py", line 71, in <module> from .WAAgentUtil import waagent File "/var/lib/waagent/Microsoft.VisualStudio.Services.TeamServicesAgentLinux-1.25.2.0/Utils/WAAgentUtil.py", line 64, in <module> waagent = imp.load_source('waagent', agentPath) ^^^^^^^^^^^^^^^ AttributeError: module 'importlib' has no attribute 'load_source' '. 'Install handler failed for the extension. More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot'`

### Repro steps

Run the GenerateResourcesAndImage.ps1 script to build an image based on Ubuntu 24.04. Use the generated Runner-Image-Ubuntu2404 in a Virtual Machine Scale Set (VMSS) and attempt to start the VMSS.

**Comment by jared-jakacky-kdi** [comment]
Following [GitHub - microsoft/vsts-azurevm-extension](https://github.com/[microsoft/vsts-azurevm-extension](https://github.com/microsoft/vsts-azurevm-extension)) repo, it appears the issue with vsts-azurevm-extension has been fixed in version 1.26.2.0 or higher, which is currently being rolled out.
