### ISSUE TITLE
Restoring NuGet packages on windows-2019 image fails (as of today)

### ISSUE THREAD

**Issue by martinfletcher-w2** [actions/virtual-environments#1411]
Working builds of a repo containing netstandard2.0 projects started failing today with following error message:

```
Starting: Restore NuGet Packages
==============================================================================
Task         : NuGet
Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Azure Artifacts and MyGet. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
Version      : 2.172.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/nuget
==============================================================================
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
C:\windows\system32\chcp.com 65001
Active code page: 65001
Detected NuGet version 5.6.0.6591 / 5.6.0+636570e68732c1f718ede9ca07802d7b1cc69aa0.636570e68732c1f718ede9ca07802d7b1cc69aa0
SYSTEMVSSCONNECTION exists true
C:\hostedtoolcache\windows\NuGet\5.6.0\x64\nuget.exe restore D:\a\1\s\MySolution.sln -Verbosity Detailed -NonInteractive -ConfigFile D:\a\1\s\nuget.config
D:\a\1\s\src\MyProject.Abstractions\MyProject.Abstractions.csproj : error : Version 3.1.401 of the .NET Core SDK requires at least version 16.7.0 of MSBuild. The current available version of MSBuild is 16.6.0.22303. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.
D:\a\1\s\src\MyProject.Abstractions\MyProject.Abstractions.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
D:\a\1\s\test\MyProject.Abstractions.UnitTests\MyProject.Abstractions.UnitTests.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
D:\a\1\s\src\MyProject\MyProject.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
D:\a\1\s\test\MyProject.UnitTests\MyProject.UnitTests.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

NuGet Version: 5.6.0.6591
MSBuild auto-detection: using msbuild version '16.6.0.22303' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
MSBuild P2P timeout [ms]: 120000
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\msbuild.exe "C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\jkqkl54a.klo.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\VssAdministrator\AppData\Local\Temp\NuGetScratch\trs0cunx.fah.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="C:\hostedtoolcache\windows\NuGet\5.6.0\x64\nuget.exe" /p:RestoreSolutionDirectory="D:\a\1\s\\" /p:RestoreConfigFile="D:\a\1\s\nuget.config" /p:SolutionDir="D:\a\1\s\\" /p:SolutionName="MySolution"
NuGet.CommandLine.ExitCodeException: Exception of type 'NuGet.CommandLine.ExitCodeException' was thrown.
   at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__63.MoveNext()
##[error]The nuget command failed with exit code(1) and error(D:\a\1\s\src\MyProject.Abstractions\MyProject.Abstractions.csproj : error : Version 3.1.401 of the .NET Core SDK requires at least version 16.7.0 of MSBuild. The current available version of MSBuild is 16.6.0.22303. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.
D:\a\1\s\src\MyProject.Abstractions\MyProject.Abstractions.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
D:\a\1\s\test\MyProject.Abstractions.UnitTests\MyProject.Abstractions.UnitTests.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
D:\a\1\s\src\MyProject\MyProject.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.
D:\a\1\s\test\MyProject.UnitTests\MyProject.UnitTests.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.)
##[error]Packages failed to restore
Finishing: Restore NuGet Packages
```

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
Packages restore successfully

**Actual behavior**
Packages fail to restore

1. Create a new C# netstandard2.0 project with VS2019 16.6.5
2. Create a build pipeline using windows-2019 agent
3. Install NuGet tool (NuGet version 5.x)
4. Add NuGet restore task to restore solution packages
5. Run build

**Comment by al-cheb** [comment]
Hello, @martinfletcher-w2 
Could you please add a step to configure `Use .NET Core task` - https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops?

**Comment by martinfletcher-w2** [comment]
Apologies, I did not mention that i already have the task in the pipeline, set to install DotNet Core SDK 3.1.x

I was able to get around this issue by specifying explicit version 3.1.107 - Although, I would have thought that any 3.1.x version should work?

**Comment by al-cheb** [comment]
@martinfletcher-w2 ,error : **Version 3.1.401 of the .NET Core SDK requires at least version 16.7.0 of MSBuild**. The current available version of **MSBuild is 16.6.0.22303**. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available.

We are planning to roll-out a new image with VS 16.7.0 in a week or two.

**Comment by al-cheb** [comment]
@martinfletcher-w2 , The image with VS 16.7 has been deployed. Could you please check you pipeline?

**Comment by al-cheb** [comment]
Feel free to open the thread if you have any concerns.

**Comment by martinfletcher-w2** [comment]
Sorry for the late reply on this issue - I can confirm that this is now resolved with the latest agent release.

Thanks for the help.
