### ISSUE TITLE
execution error: Finder got an error: AppleEvent timed out. (-1712)

### ISSUE THREAD

**Issue by mitm001** [actions/virtual-environments#1541]
**Description**  
I am hitting this issue running java jpackage from an AdoptOpenJDK install with the github runner.

```
 Current runner version: '2.273.0'
Operating System
  Mac OS X
  10.15.6
  19G2021
Virtual Environment
  Environment: macos-10.15
  Version: 20200829.1
  Included Software: https://github.com/actions/virtual-environments/blob/macos-10.15/20200829.1/images/macos/macos-10.15-Readme.md
```
```
2020-09-03 00:48:36.975 diskimages-helper[1172:8455] _postflightMountPointsAfterDAMount: disk2 aborting because no mount point found.
/dev/disk2          	GUID_partition_scheme          	
/dev/disk2s1        	Apple_HFS                      	/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/jdk.incubator.jpackage6368649391411397710/images/packit
Running [/usr/bin/SetFile, -c, icnC, /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/jdk.incubator.jpackage6368649391411397710/images/packit/.VolumeIcon.icns]
Running [/usr/bin/SetFile, -a, C, /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/jdk.incubator.jpackage6368649391411397710/images/packit]
Running [osascript, /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/jdk.incubator.jpackage6368649391411397710/config/packit-dmg-setup.scpt]
/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/jdk.incubator.jpackage6368649391411397710/config/packit-dmg-setup.scpt:60:109: execution error: Finder got an error: AppleEvent timed out. (-1712)
java.io.IOException: Command [osascript, /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/jdk.incubator.jpackage6368649391411397710/config/packit-dmg-setup.scpt] exited with 1 code
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.Executor.executeExpectSuccess(Executor.java:73)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.IOUtils.exec(IOUtils.java:179)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.IOUtils.exec(IOUtils.java:150)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.MacDmgBundler.buildDMG(MacDmgBundler.java:348)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.MacDmgBundler.bundle(MacDmgBundler.java:75)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.MacDmgBundler.execute(MacDmgBundler.java:451)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.Arguments.generateBundle(Arguments.java:641)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.Arguments.processArguments(Arguments.java:514)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.main.Main.execute(Main.java:97)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.main.Main.main(Main.java:51)
```
**Area for Triage**:  
Scripting and command line
Apple

**Bug**:  

**Virtual environments affected**  
- [X] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
No exception build

**Actual behavior**  
Running jpackage on Mac OS runner throws exception after timeout every run. Since this happens every build, and github charges you 10x1 for minutes in private accounts, this has a huge impact on github actions alloted time.

Similar closed issue? #553

**Repro steps**  
https://github.com/mitm001/packit/actions

Pick any build, all have MacOs build.

1. Install AdoptOpenJDK 
    #https://github.com/joschi/setup-jdk
    - name: Set up OpenJDK 
      uses: joschi/setup-jdk@v2
      with:
        java-version: ${{ matrix.java }}
        architecture: x64
2. Run gradle.build packit command from repo.

**Comment by maxim-lobanov** [comment]
Could be related to the active issue about modal window https://github.com/actions/virtual-environments/issues/1520

**Comment by miketimofeev** [comment]
Hi @mitm001! Small update: I'm able to reproduce the issue, here is the screenshot on what's happened in the VM
![image](https://user-images.githubusercontent.com/48208649/92128819-74cf1200-ee0b-11ea-9599-dd6166df7779.png)
We'll investigate possible solutions.

**Comment by miketimofeev** [comment]
@mitm001 could you please add these lines before ./gradlew build? This resolves the issue for me
```
JavaPath=$(which java)
sqlite3 "$HOME/Library/Application Support/com.apple.TCC/TCC.db" "insert into access (service, client, client_type, allowed, prompt_count, indirect_object_identifier_type, indirect_object_identifier) values ('kTCCServiceAppleEvents', '$JavaPath', 1, 1, 1, 0, 'com.apple.finder')"
```

**Comment by mitm001** [comment]
Yes, this works. Thank you.

I am not familiar with this, is this something I should open another issue on?
```
DI_kextDriveDisconnect: could not disconnect from IOHDIXHDDrive object - 268435459
diskimages-helper: DI_kextDriveDisconnect returned 268435459 ((ipc/send) invalid destination port).

2020-09-03 16:28:43.912 diskimages-helper[1032:6951] _postflightMountPointsAfterDAMount: disk2s1 aborting because disk image has no band size specified.
2020-09-03 16:28:43.913 diskimages-helper[1032:6954] _mountDevEntries: disk2s1 aborting mountpoint postflight because disk image has no band size specified.
2020-09-03 16:28:43.915 diskimages-helper[1032:6951] _postflightMountPointsAfterDAMount: disk2 aborting because no mount point found.
```

**Comment by miketimofeev** [comment]
@mitm001 it looks like some sort of warning,  I haven't seen such kind of errors before and judging by the logs the package created successfully after all
```
DIDiskImageNewWithBackingStore: CUDIFDiskImage
DIDiskImageNewWithBackingStore: instantiator returned 0
Elapsed Time:  1.050s
File size: 58752880 bytes, Checksum: CRC32 $69DF94F9
Sectors processed: 322772, 281644 compressed
Speed: 130.9Mbytes/sec
Savings: 64.4%
DIDiskImageConvertWithDiskImage: converter returned 0
created: /Users/runner/work/1/s/packit/build/jpackage/packit-2.1.0.dmghdiutil: convert: result: 0

Result DMG installer for packit: /Users/runner/work/1/s/packit/build/jpackage/packit-2.1.0.dmg.
Succeeded in building Mac DMG Package package

```

**Comment by mitm001** [comment]
Ok, I will close this, thanks for the fix.
