### ISSUE TITLE
Az CLI issue in Windows Server 2019

### ISSUE THREAD

**Issue by vexingpos** [actions/virtual-environments#2329]
**Description**  
Running a simple `az --version` command on a self-hosted Windows 2019 agent throws the following exception.

````
2020-12-21T22:53:27.6841598Z [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n AzureCloud"
2020-12-21T22:53:35.5928595Z CLIInternalError: The command failed with an unexpected error. Here is the traceback:
2020-12-21T22:53:35.5976953Z ##[error]Error Code: [1]
2020-12-21T22:53:35.5998961Z [WinError 5] Access is denied: 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\azure-devops\\azure_devops-0.18.0.dist-info'
2020-12-21T22:53:35.6004845Z Traceback (most recent call last):
2020-12-21T22:53:35.6014593Z ##[error]Script failed with error: CLIInternalError: The command failed with an unexpected error. Here is the traceback:
[WinError 5] Access is denied: 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\azure-devops\\azure_devops-0.18.0.dist-info'
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-2huwp6jm\knack\cli.py", line 215, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 509, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\__init__.py", line 436, in load_command_table
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\__init__.py", line 307, in _update_command_table_from_extensions
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\extension\__init__.py", line 156, in get_metadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ow5xv8av\pkginfo\wheel.py", line 16, in __init__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ow5xv8av\pkginfo\distribution.py", line 108, in extractMetadata
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ow5xv8av\pkginfo\wheel.py", line 33, in read
PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\azure-devops\\azure_devops-0.18.0.dist-info'
To open an issue, please run: 'az feedback'

2020-12-21T22:53:35.6062300Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-2huwp6jm\knack\cli.py", line 215, in invoke
2020-12-21T22:53:35.6084685Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\commands\__init__.py", line 509, in execute
2020-12-21T22:53:35.6086734Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\__init__.py", line 436, in load_command_table
2020-12-21T22:53:35.6088148Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\__init__.py", line 307, in _update_command_table_from_extensions
2020-12-21T22:53:35.6090427Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-0ydpnxq9\azure\cli\core\extension\__init__.py", line 156, in get_metadata
2020-12-21T22:53:35.6092054Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ow5xv8av\pkginfo\wheel.py", line 16, in __init__
2020-12-21T22:53:35.6093204Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ow5xv8av\pkginfo\distribution.py", line 108, in extractMetadata
2020-12-21T22:53:35.6094293Z   File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpacked-wheel-ow5xv8av\pkginfo\wheel.py", line 33, in read
2020-12-21T22:53:35.6095469Z PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\azure-devops\\azure_devops-0.18.0.dist-info'
````

**Area for Triage**: 
* Deployment/Release
* Scripting and command line 

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
Should print out version

**Actual behavior**  
See above.

**Repro steps**  
Create a pipeline using your self-hosted Windows 2019 agent and add the CLI task. Run an inline script consisting of `az --version`

**UAC considerations**
Someone reported a similar issue over here: #1682. The explanation there was that the token needs to be `Mandatory Label\High Mandatory Level`. I ran `whoami /groups` and the output is as follows
````
Group Name                                                           Type             SID                                              Attributes                                                     
==================================================================== ================ ================================================ ===============================================================
Everyone                                                             Well-known group S-1-1-0                                          Mandatory group, Enabled by default, Enabled group             
[redacted_hostname]\VSTS_AgentService_G0e2d6                         Alias            S-1-5-21-1136344280-3482314079-3147039972-1003   Mandatory group, Enabled by default, Enabled group             
BUILTIN\Users                                                        Alias            S-1-5-32-545                                     Mandatory group, Enabled by default, Enabled group             
NT AUTHORITY\SERVICE                                                 Well-known group S-1-5-6                                          Mandatory group, Enabled by default, Enabled group             
CONSOLE LOGON                                                        Well-known group S-1-2-1                                          Mandatory group, Enabled by default, Enabled group             
NT AUTHORITY\Authenticated Users                                     Well-known group S-1-5-11                                         Mandatory group, Enabled by default, Enabled group             
NT AUTHORITY\This Organization                                       Well-known group S-1-5-15                                         Mandatory group, Enabled by default, Enabled group             
LOCAL                                                                Well-known group S-1-2-0                                          Mandatory group, Enabled by default, Enabled group             
Authentication authority asserted identity                           Well-known group S-1-18-1                                         Mandatory group, Enabled by default, Enabled group             
Mandatory Label\High Mandatory Level                                 Label            S-1-16-12288                                                                                                    
````

Notice how the last line shows High mandatory level. So in theory I shouldn't be having permission issues - I must be missing something?

**Comment by maxim-lobanov** [comment]
Hello @vexingpos , In this repository we manage only Hosted agents.
Since you use self-hosted agent that was created and configured by you, we can't help with debugging.
If you deploy self-hosted agent in Azure, I suggest trying [this answer](https://github.com/actions/virtual-environments/issues/1682#issuecomment-702559126). If it doesn't help, I suggest digging this repo to see how we install Azure CLI on Hosted machines and try to use the same approach.

**Comment by vexingpos** [comment]
Hi @maxim-lobanov 

I'm not sure this issue can be closed straight-away. 

I understand it's a self-hosted agent but it was built using the same Packer configs that you guys use to build your own Hosted agents. My agent was built off b6b55afeaa2e6bb8fc0f8746223032317fbc32f0 (i.e. Saturday's cut of the main branch).

@al-cheb  Any thoughts on whether there's a further UAC issue that needs resolving here?

**Comment by al-cheb** [comment]
@vexingpos, Looks like `BUILTIN\Administrators` group is missing in the token.
![image](https://user-images.githubusercontent.com/47745270/102885289-2a2de000-4464-11eb-8ef6-e94ca1b35789.png)

**Comment by vexingpos** [comment]
Looks like UAC somehow got re-enabled on the VM. I disabled it again and the `BUILTIN\Administators` token is present now. Thanks for your help!
