### ISSUE TITLE
build jekyll site Error with ubuntu-latest

### ISSUE THREAD

**Issue by archzi** [actions/virtual-environments#2823]
**Description**  
When I used the `ubuntu-latest` in my github jobs and build My jekyll blog with `bundle exec jekyll b -d` command, and I got a following error。
```
Run bundle exec jekyll b -d "_site$BASE_URL"
bundler: failed to load command: jekyll (/home/runner/vendor/bundle/ruby/2.7.0/bin/jekyll)
LoadError: libffi.so.6: cannot open shared object file: No such file or directory - /home/runner/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi_c.so
  /home/runner/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi.rb:6:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `require_relative'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/lib/jekyll.rb:195:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/lib/jekyll.rb:195:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/exe/jekyll:8:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/exe/jekyll:8:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `load'
  /home/runner/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `<top (required)>'
Error: Process completed with exit code 1.
```
and I looked up my actions build log that built in some days ago, I found It used the `ubuntu-18.04` ,and Today It used `ubuntu-20.04` 

The Gemfile follows 
```
PATH
  remote: .
  specs:
    jekyll-theme-chirpy (3.2.1)
      jekyll (~> 4.1)
      jekyll-archives (~> 2.2)
      jekyll-paginate (~> 1.1)
      jekyll-redirect-from (~> 0.16)
      jekyll-seo-tag (~> 2.7)
      jekyll-sitemap (~> 1.4)

GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.7.0)
      public_suffix (>= 2.0.2, < 5.0)
    colorator (1.1.0)
    concurrent-ruby (1.1.8)
    em-websocket (0.5.2)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    ethon (0.12.0)
      ffi (>= 1.3.0)
    eventmachine (1.2.7)
    ffi (1.14.2)
    forwardable-extended (2.6.0)
    html-proofer (3.18.5)
      addressable (~> 2.3)
      mercenary (~> 0.3)
      nokogumbo (~> 2.0)
      parallel (~> 1.3)
      rainbow (~> 3.0)
      typhoeus (~> 1.3)
      yell (~> 2.0)
    http_parser.rb (0.6.0)
    i18n (1.8.9)
      concurrent-ruby (~> 1.0)
    jekyll (4.2.0)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (~> 2.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (~> 0.4.0)
      pathutil (~> 0.9)
      rouge (~> 3.0)
      safe_yaml (~> 1.0)
      terminal-table (~> 2.0)
    jekyll-archives (2.2.1)
      jekyll (>= 3.6, < 5.0)
    jekyll-paginate (1.1.0)
    jekyll-redirect-from (0.16.0)
      jekyll (>= 3.3, < 5.0)
    jekyll-sass-converter (2.1.0)
      sassc (> 2.0.1, < 3.0)
    jekyll-seo-tag (2.7.1)
      jekyll (>= 3.8, < 5.0)
    jekyll-sitemap (1.4.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    kramdown (2.3.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    liquid (4.0.3)
    listen (3.4.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.4.0)
    nokogiri (1.11.1-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.11.1-x86_64-linux)
      racc (~> 1.4)
    nokogumbo (2.0.4)
      nokogiri (~> 1.8, >= 1.8.4)
    parallel (1.20.1)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (4.0.6)
    racc (1.5.2)
    rainbow (3.0.0)
    rb-fsevent (0.10.4)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.4)
    rouge (3.26.0)
    safe_yaml (1.0.5)
    sassc (2.4.0)
      ffi (~> 1.9)
    terminal-table (2.0.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    thread_safe (0.3.6)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    tzinfo (1.2.9)
      thread_safe (~> 0.1)
    tzinfo-data (1.2021.1)
      tzinfo (>= 1.0.0)
    unicode-display_width (1.7.0)
    wdm (0.1.1)
    yell (2.2.2)

PLATFORMS
  x86_64-darwin-20
  x86_64-linux

DEPENDENCIES
  html-proofer (~> 3.18)
  jekyll-theme-chirpy!
  tzinfo (~> 1.2)
  tzinfo-data
  wdm (~> 0.1.1)

BUNDLED WITH
   2.2.11

```

**Area for Triage**:  

**Bug**:  
It seems like the `ubuntu-latest` loses some libs?
**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Environment: ubuntu-20.04
  Version: 20210219.1

**Expected behavior**  
A description of what you expected to happen.

**Actual behavior**  
```
Run bundle exec jekyll b -d "_site$BASE_URL"
bundler: failed to load command: jekyll (/home/runner/vendor/bundle/ruby/2.7.0/bin/jekyll)
LoadError: libffi.so.6: cannot open shared object file: No such file or directory - /home/runner/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi_c.so
  /home/runner/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi.rb:6:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `require_relative'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/lib/jekyll.rb:195:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/lib/jekyll.rb:195:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/exe/jekyll:8:in `require'
  /home/runner/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/exe/jekyll:8:in `<top (required)>'
  /home/runner/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `load'
  /home/runner/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `<top (required)>'
Error: Process completed with exit code 1.
```

**Comment by maxim-lobanov** [comment]
@archzi , See https://github.com/actions/virtual-environments/issues/1816
It is expected that software list is different for Ubuntu 18.04 and 20.04. I suggest setting up `ubuntu-18.04` explicitly in your YAML to switch back to 18.04

**Comment by archzi** [comment]
@maxim-lobanov Thank your suggestion. I have done it. I thought it's would be backwards compatible.

**Comment by maxim-lobanov** [comment]
@archzi , images are pretty similar and in most of the cases have backward compatibility but some narrow places are not compatible.
As for this particular case, it is known issue, see https://github.com/ffi/ffi/issues/773
The Ubuntu 20.04 images contain `libffi7` by default instead of `libffi6` like on Ubuntu 18.04. Based on the issue above they look incompatible to each other. And we can't install both versions side by side.

If you would like to use `libffi6` on Ubuntu 20.04, you can try to re-install it and replace `libffi7` with `libffi6` in runtime but we can't do that on base image due to unpredictable impact.
