### ISSUE TITLE
azure devops windows image - unable install pip ERROR: No matching distribution found for paho-mqtt==1.5.0

### ISSUE THREAD

**Issue by roopsduhra** [actions/virtual-environments#3143]
**Tool information**
- Tool name: Azure DevOps
- Tool license: <n/a->
- Add or update? <Add>
- Desired version:  paho-mqtt==1.5.0
- Approximate size: <>
- If this is an add request:
  - Brief description of tool: azure devops pipelines
  - URL for tool's homepage: https://dev.azure.com/
  - Provide a basic test case to validate the tool's functionality: 
 <- task: AzureCLI@2
  inputs:
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az extension add --name azure-iot --debug 
      az extension update  --name azure-iot>

**Area for Triage**:

We are trying to install az extension azure-iot  and receives the errors as per logs below. it was working on the 31st March and stops working after.
please see the logs for the failure below for the error, I believe the issue is with version pip 21.0.1 (python 3.7)

09T14:03:04.1013749Z Given no hashes to check 1 links for project 'paho-mqtt': discarding no candidates
2021-04-09T14:03:04.1014366Z Collecting paho-mqtt==1.5.0
2021-04-09T14:03:04.1015169Z   Created temporary directory: C:\Users\VSSADM~1\AppData\Local\Temp\pip-unpack-2aapvqmm
2021-04-09T14:03:04.1016025Z   https://files.pythonhosted.org:443 "GET /packages/59/11/1dd5c70f0f27a88a3a05772cd95f6087ac479fac66d9c7752ee5e16ddbbc/paho-mqtt-1.5.0.tar.gz HTTP/1.1" 200 99525
2021-04-09T14:03:04.1016633Z   Downloading paho-mqtt-1.5.0.tar.gz (99 kB)
2021-04-09T14:03:04.1017464Z   Added paho-mqtt==1.5.0 from https://files.pythonhosted.org/packages/59/11/1dd5c70f0f27a88a3a05772cd95f6087ac479fac66d9c7752ee5e16ddbbc/paho-mqtt-1.5.0.tar.gz#sha256=e3d286198baaea195c8b3bc221941d25a3ab0e1507fc1779bdb7473806394be4 (from azure-iot==0.10.10) to build tracker 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\pip-req-tracker-wvv60fkc'
2021-04-09T14:03:04.1018597Z     Running setup.py (path:C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-fw0owoj7\paho-mqtt_f40f0ae13e6e4bc281ccb3a885a13263\setup.py) egg_info for package paho-mqtt
2021-04-09T14:03:04.1019231Z     Created temporary directory: C:\Users\VSSADM~1\AppData\Local\Temp\pip-pip-egg-info-7k4nx1ew
2021-04-09T14:03:04.1019670Z     Running command python setup.py egg_info
2021-04-09T14:03:04.1020220Z     C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'include_package_data'
2021-04-09T14:03:04.1020933Z     C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
2021-04-09T14:03:04.1021645Z     C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'zip_safe'
2021-04-09T14:03:04.1022357Z     C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
2021-04-09T14:03:04.1023066Z     C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
2021-04-09T14:03:04.1023758Z     C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'extras_require'
2021-04-09T14:03:04.1024337Z     usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
2021-04-09T14:03:04.1024736Z        or: setup.py --help [cmd1 cmd2 ...]
2021-04-09T14:03:04.1026091Z        or: setup.py --help-commands
2021-04-09T14:03:04.1026477Z        or: setup.py cmd --help
2021-04-09T14:03:04.1026641Z 
2021-04-09T14:03:04.1026967Z     error: invalid command 'egg_info'
2021-04-09T14:03:04.1028050Z WARNING: Discarding https://files.pythonhosted.org/packages/59/11/1dd5c70f0f27a88a3a05772cd95f6087ac479fac66d9c7752ee5e16ddbbc/paho-mqtt-1.5.0.tar.gz#sha256=e3d286198baaea195c8b3bc221941d25a3ab0e1507fc1779bdb7473806394be4 (from https://pypi.org/simple/paho-mqtt/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2021-04-09T14:03:04.1029296Z ERROR: Could not find a version that satisfies the requirement paho-mqtt==1.5.0 (from azure-iot)
2021-04-09T14:03:04.1029938Z ERROR: No matching distribution found for paho-mqtt==1.5.0
2021-04-09T14:03:04.1030268Z Exception information:
2021-04-09T14:03:04.1030601Z Traceback (most recent call last):
2021-04-09T14:03:04.1031103Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 122, in resolve
2021-04-09T14:03:04.1031783Z     requirements, max_rounds=try_to_avoid_resolution_too_deep,
2021-04-09T14:03:04.1032308Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 453, in resolve
2021-04-09T14:03:04.1032957Z     state = resolution.resolve(requirements, max_rounds=max_rounds)
2021-04-09T14:03:04.1033509Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 357, in resolve
2021-04-09T14:03:04.1033972Z     raise ResolutionImpossible(causes)
2021-04-09T14:03:04.1034765Z pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('paho-mqtt==1.5.0'), parent=LinkCandidate('file:///C:/Users/VSSADM%7E1/AppData/Local/Temp/tmp5ovjglbg/azure_iot-0.10.10-py3-none-any.whl'))]
2021-04-09T14:03:04.1035727Z 
2021-04-09T14:03:04.1036095Z The above exception was the direct cause of the following exception:
2021-04-09T14:03:04.1036348Z 
2021-04-09T14:03:04.1036822Z Traceback (most recent call last):
2021-04-09T14:03:04.1037377Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_internal\cli\base_command.py", line 189, in _main
2021-04-09T14:03:04.1038518Z     status = self.run(options, args)
2021-04-09T14:03:04.1039020Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_internal\cli\req_command.py", line 178, in wrapper
2021-04-09T14:03:04.1039477Z     return func(self, options, args)
2021-04-09T14:03:04.1039959Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_internal\commands\install.py", line 317, in run
2021-04-09T14:03:04.1040457Z     reqs, check_supported_wheels=not options.target_dir
2021-04-09T14:03:04.1040970Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 127, in resolve
2021-04-09T14:03:04.1041453Z     six.raise_from(error, e)
2021-04-09T14:03:04.1041787Z   File "<string>", line 3, in raise_from
2021-04-09T14:03:04.1042242Z pip._internal.exceptions.DistributionNotFound: No matching distribution found for paho-mqtt==1.5.0
2021-04-09T14:03:04.1043206Z Removed paho-mqtt==1.5.0 from https://files.pythonhosted.org/packages/59/11/1dd5c70f0f27a88a3a05772cd95f6087ac479fac66d9c7752ee5e16ddbbc/paho-mqtt-1.5.0.tar.gz#sha256=e3d286198baaea195c8b3bc221941d25a3ab0e1507fc1779bdb7473806394be4 (from azure-iot==0.10.10) from build tracker 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\pip-req-tracker-wvv60fkc'
2021-04-09T14:03:04.1044151Z Removed build tracker: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\pip-req-tracker-wvv60fkc'
2021-04-09T14:03:04.1044407Z 
2021-04-09T14:03:04.1045340Z DEBUG: cli.azure.cli.core.extension.operations: Command '['C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\python.exe', '-m', 'pip', 'install', '--target', 'C:\\Program Files\\Common Files\\AzureCliExtensionDirectory\\azure-iot', 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmp5ovjglbg\\azure_iot-0.10.10-py3-none-any.whl', '-vv', '--disable-pip-version-check', '--no-cache-dir']' returned non-zero exit status 1.
2021-04-09T14:03:04.1046565Z DEBUG: cli.azure.cli.core.extension.operations: Pip failed so deleting anything we might have installed at C:\Program Files\Common Files\AzureCliExtensionDirectory\azure-iot
2021-04-09T14:03:04.2572490Z DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
2021-04-09T14:03:04.2577183Z DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
2021-04-09T14:03:04.2577982Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
2021-04-09T14:03:04.2581238Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 660, in execute
2021-04-09T14:03:04.2582235Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 723, in _run_jobs_serially
2021-04-09T14:03:04.2583074Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 716, in _run_job
2021-04-09T14:03:04.2583852Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\six.py", line 703, in reraise
2021-04-09T14:03:04.2584757Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 694, in _run_job
2021-04-09T14:03:04.2586605Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 331, in __call__
2021-04-09T14:03:04.2589690Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 811, in default_command_handler
2021-04-09T14:03:04.2590580Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/extension/custom.py", line 18, in add_extension_cmd
2021-04-09T14:03:04.2591441Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 327, in add_extension
2021-04-09T14:03:04.2592396Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 163, in _add_whl_ext
2021-04-09T14:03:04.2593373Z knack.util.CLIError: An error occurred. Pip failed with status code 1. Use --debug for more information.
2021-04-09T14:03:04.2593780Z 
2021-04-09T14:03:04.2594418Z ERROR: cli.azure.cli.core.azclierror: An error occurred. Pip failed with status code 1. Use --debug for more information.
2021-04-09T14:03:04.2595208Z ERROR: cli.azure.cli.core.azclierror: An error occurred. Pip failed with status code 1. Use --debug for more information.
2021-04-09T14:03:04.2595972Z DEBUG: cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x03CCD8E8>]
2021-04-09T14:03:04.2596609Z INFO: az_command_data_logger: exit code: 1
2021-04-09T14:03:04.2597205Z INFO: cli.__main__: Command ran in 9.741 seconds (init: 0.234, invoke: 9.508)
2021-04-09T14:03:04.3096771Z INFO: telemetry.save: Save telemetry record of length 3067 in cache
2021-04-09T14:03:04.3098936Z WARNING: telemetry.check: Negative: The D:\a\_temp\.azclitask\telemetry.txt was modified at 2021-04-09 14:02:51.499622, which in less than 600.000000 s
2021-04-09T14:03:05.1428779Z ERROR: The extension azure-iot is not installed.
2021-04-09T14:03:05.4067811Z ##[debug]$LASTEXITCODE: 1
2021-04-09T14:03:05.4443445Z ##[debug]Exit code 1 received from tool 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
2021-04-09T14:03:05.4449897Z ##[debug]STDIO streams have closed for tool 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
2021-04-09T14:03:05.4473762Z ##[debug]task result: Failed

**Question, Bug, or Feature?**:
<"Bug">

**Virtual environments affected**
- [ ] Windows Server 2019

**Can this tool be installed during the build?**

**Tool installation time in runtime**
<yes>

**Are you willing to submit a PR?**

**Comment by miketimofeev** [comment]
Hi @roopsduhra!
We've started the investigation and get back with the results shortly.

**Comment by miketimofeev** [comment]
@roopsduhra Azure Cli has its own Python distribution, but the latest az-cli version seems to have a lack of setuptools and wheel python modules. The workaround is to install these modules in runtime:
```
$azPython = "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe"
& $azpython -m pip install setuptools
& $azpython -m pip install install wheel
```

**Comment by miketimofeev** [comment]
@roopsduhra Good news, azure-cli 2.22 doesn't have the issue. The new image with it on board will be deployed in the next 3-4 days.

**Comment by roopsduhra** [comment]
@miketimofeev, can you please let me know once new images is deployed, many thanks for the update.

**Comment by miketimofeev** [comment]
@roopsduhra the deployment completed!
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Comment by jiasli** [comment]
This issue has been fixed by https://github.com/Azure/azure-cli/pull/17432 since 2.22.0.

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/18703#issuecomment-873843943

**Comment by jiasli** [comment]
This issue has been fixed by https://github.com/Azure/azure-cli/pull/17432 since Azure CLI 2.22.0.
