### ISSUE TITLE
Java build breakage with MacOS 10.14 (version: '20210413.1')

### ISSUE THREAD

**Issue by gwang-msft** [actions/virtual-environments#3195]
**Description**  
After yesterday's upgrade to 20210413.1 all our java builds have started failing with 'net.rubygrapefruit.platform.NativeException: Could not query file systems: could not determine file system attributes (errno 5: Input/output error)'

We suspect that the Gradle 7.0 was the reason of the failure, the previous image version 20210405.1 where the build can finish, has Gradle 6.8.3

Error messages 
```
2021-04-16T08:35:48.1371460Z To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.0/userguide/gradle_daemon.html#sec:disabling_the_daemon.
2021-04-16T08:35:48.1431220Z Daemon will be stopped at the end of the build 
2021-04-16T08:35:48.1436420Z > Task :spotlessJava UP-TO-DATE
2021-04-16T08:35:48.1486680Z > Task :compileJava UP-TO-DATE
2021-04-16T08:35:48.1538510Z > Task :processResources NO-SOURCE
2021-04-16T08:35:48.1619970Z > Task :classes UP-TO-DATE
2021-04-16T08:35:48.1644260Z > Task :generatePomFileForMavenPublication
2021-04-16T08:35:48.1688500Z > Task :allJar
2021-04-16T08:35:48.1722270Z > Task :javadoc
2021-04-16T08:35:48.1793070Z > Task :javadocJar
2021-04-16T08:35:48.1815330Z > Task :sourcesJar
2021-04-16T08:35:48.1836160Z > Task :cmakeBuild
2021-04-16T08:35:48.1841610Z 
2021-04-16T08:35:48.1903990Z BUILD SUCCESSFUL in 52s
2021-04-16T08:35:48.1940010Z 8 actionable tasks: 6 executed, 2 up-to-date
2021-04-16T08:35:48.1953310Z Unable to watch the file system for changes
2021-04-16T08:35:48.2003490Z net.rubygrapefruit.platform.NativeException: Could not query file systems: could not determine file system attributes (errno 5: Input/output error)
2021-04-16T08:35:48.2032890Z 	at net.rubygrapefruit.platform.internal.PosixFileSystems.getFileSystems(PosixFileSystems.java:32)
2021-04-16T08:35:48.2043290Z 	at org.gradle.internal.watch.vfs.impl.DefaultWatchableFileSystemDetector.detectUnsupportedFileSystems(DefaultWatchableFileSystemDetector.java:64)
2021-04-16T08:35:48.2137430Z 	at org.gradle.internal.watch.registry.impl.WatchableHierarchies.removeUnwatchableFileSystems(WatchableHierarchies.java:113)
2021-04-16T08:35:48.2147300Z 	at org.gradle.internal.watch.registry.impl.WatchableHierarchies.removeUnwatchableContent(WatchableHierarchies.java:82)
2021-04-16T08:35:48.2242030Z 	at org.gradle.internal.watch.registry.impl.HierarchicalFileWatcherUpdater.buildFinished(HierarchicalFileWatcherUpdater.java:98)
2021-04-16T08:35:48.2255710Z 	at org.gradle.internal.watch.registry.impl.DefaultFileWatcherRegistry.buildFinished(DefaultFileWatcherRegistry.java:146)
2021-04-16T08:35:48.2343290Z 	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem$2.lambda$call$0(WatchingVirtualFileSystem.java:199)
2021-04-16T08:35:48.2363220Z 	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.withWatcherChangeErrorHandling(WatchingVirtualFileSystem.java:320)
2021-04-16T08:35:48.2450250Z 	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.access$1000(WatchingVirtualFileSystem.java:53)
2021-04-16T08:35:48.2458140Z 	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem$2.call(WatchingVirtualFileSystem.java:199)
2021-04-16T08:35:48.2473980Z 	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem$2.call(WatchingVirtualFileSystem.java:179)
2021-04-16T08:35:48.2570700Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
2021-04-16T08:35:48.2575270Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
2021-04-16T08:35:48.2581160Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
2021-04-16T08:35:48.2673670Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
2021-04-16T08:35:48.2678830Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
2021-04-16T08:35:48.2694480Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
2021-04-16T08:35:48.2781270Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
2021-04-16T08:35:48.2800710Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
2021-04-16T08:35:48.2832450Z 	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
2021-04-16T08:35:48.2883710Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
2021-04-16T08:35:48.2903120Z 	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.lambda$beforeBuildFinished$5(WatchingVirtualFileSystem.java:179)
2021-04-16T08:35:48.2988250Z 	at org.gradle.internal.vfs.impl.VfsRootReference.update(VfsRootReference.java:40)
2021-04-16T08:35:48.3004240Z 	at org.gradle.internal.watch.vfs.impl.WatchingVirtualFileSystem.beforeBuildFinished(WatchingVirtualFileSystem.java:179)
2021-04-16T08:35:48.3048980Z 	at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:93)
2021-04-16T08:35:48.3106400Z 	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
2021-04-16T08:35:48.3123240Z 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:49)
2021-04-16T08:35:48.3151730Z 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:44)
2021-04-16T08:35:48.3155410Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
2021-04-16T08:35:48.3209240Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
2021-04-16T08:35:48.3255190Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
2021-04-16T08:35:48.3318280Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
2021-04-16T08:35:48.3326970Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
2021-04-16T08:35:48.3358950Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
2021-04-16T08:35:48.3425390Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
2021-04-16T08:35:48.3462970Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
2021-04-16T08:35:48.3465040Z 	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
2021-04-16T08:35:48.3467560Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
2021-04-16T08:35:48.3533510Z 	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:44)
2021-04-16T08:35:48.3551170Z 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.lambda$execute$0(InProcessBuildActionExecuter.java:59)
2021-04-16T08:35:48.3569000Z 	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:86)
2021-04-16T08:35:48.3638020Z 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:58)
2021-04-16T08:35:48.3651670Z 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
2021-04-16T08:35:48.3679880Z 	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.lambda$execute$0(BuildTreeScopeLifecycleBuildActionExecuter.java:34)
2021-04-16T08:35:48.3695710Z 	at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:53)
2021-04-16T08:35:48.3747070Z 	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:33)
2021-04-16T08:35:48.3762200Z 	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:28)
2021-04-16T08:35:48.3792970Z 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:104)
2021-04-16T08:35:48.3858780Z 	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:55)
2021-04-16T08:35:48.3886590Z 	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:64)
2021-04-16T08:35:48.3895460Z 	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:37)
2021-04-16T08:35:48.3967910Z 	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.lambda$execute$0(SessionScopeLifecycleBuildActionExecuter.java:54)
2021-04-16T08:35:48.3999440Z 	at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:67)
2021-04-16T08:35:48.4027290Z 	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:50)
2021-04-16T08:35:48.4106640Z 	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:36)
2021-04-16T08:35:48.4129890Z 	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
2021-04-16T08:35:48.4214720Z 	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
2021-04-16T08:35:48.4232410Z 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
2021-04-16T08:35:48.4250620Z 	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
2021-04-16T08:35:48.4321790Z 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:58)
2021-04-16T08:35:48.4352560Z 	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:42)
2021-04-16T08:35:48.4426710Z 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
2021-04-16T08:35:48.4453490Z 	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
2021-04-16T08:35:48.4529940Z 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
2021-04-16T08:35:48.4555620Z 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
2021-04-16T08:35:48.4657300Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2021-04-16T08:35:48.4658830Z 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
2021-04-16T08:35:48.4759440Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2021-04-16T08:35:48.4760980Z 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
2021-04-16T08:35:48.4861790Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2021-04-16T08:35:48.4962100Z 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
2021-04-16T08:35:48.4971830Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2021-04-16T08:35:48.4989530Z 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
2021-04-16T08:35:48.5073420Z 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
2021-04-16T08:35:48.5074840Z 	at org.gradle.util.Swapper.swap(Swapper.java:38)
2021-04-16T08:35:48.5080740Z 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
2021-04-16T08:35:48.5178220Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2021-04-16T08:35:48.5280440Z 	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:50)
2021-04-16T08:35:48.5284590Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2021-04-16T08:35:48.5392420Z 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
2021-04-16T08:35:48.5480470Z 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
2021-04-16T08:35:48.5495910Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2021-04-16T08:35:48.5527100Z 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
2021-04-16T08:35:48.5598500Z 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
2021-04-16T08:35:48.5629500Z 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
2021-04-16T08:35:48.5647100Z 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
2021-04-16T08:35:48.5660010Z 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
2021-04-16T08:35:48.5713560Z 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2021-04-16T08:35:48.5731740Z 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
2021-04-16T08:35:48.5764010Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-04-16T08:35:48.5816960Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-04-16T08:35:48.5868190Z 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
2021-04-16T08:35:48.5939930Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2021-04-16T08:35:48.5971590Z Starting a Gradle Daemon (subsequent builds will be faster)
2021-04-16T08:35:48.6074540Z > Task :preBuild UP-TO-DATE
2021-04-16T08:35:48.6077360Z > Task :preDebugBuild UP-TO-DATE
2021-04-16T08:35:48.6146640Z > Task :compileDebugAidl NO-SOURCE
2021-04-16T08:35:48.6254840Z > Task :compileDebugRenderscript NO-SOURCE
2021-04-16T08:35:48.6357110Z > Task :checkDebugManifest FAILED
2021-04-16T08:35:48.6382380Z 
2021-04-16T08:35:48.6400820Z FAILURE: Build failed with an exception.
2021-04-16T08:35:48.6461740Z 
2021-04-16T08:35:48.6489530Z * What went wrong:
2021-04-16T08:35:48.6565110Z A problem was found with the configuration of task ':checkDebugManifest' (type 'CheckManifest').
2021-04-16T08:35:48.6628860Z   - Type 'CheckManifest' property 'manifest' has @Input annotation used on property of type 'File'.
2021-04-16T08:35:48.6648760Z     
2021-04-16T08:35:48.6677420Z     Reason: A property of type 'File' annotated with @Input cannot determine how to interpret the file.
2021-04-16T08:35:48.6730990Z     
2021-04-16T08:35:48.6787760Z     Possible solutions:
2021-04-16T08:35:48.6826050Z       1. Annotate with @InputFile for regular files.
2021-04-16T08:35:48.6838690Z       2. Annotate with @InputDirectory for directories.
2021-04-16T08:35:48.6932880Z       3. If you want to track the path, return File.absolutePath as a String and keep @Input.
2021-04-16T08:35:48.6936450Z     
2021-04-16T08:35:48.6941070Z     Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#incorrect_use_of_input_annotation for more details about this problem.
2021-04-16T08:35:48.7034500Z 
2021-04-16T08:35:48.7037790Z * Try:
2021-04-16T08:35:48.7048000Z Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
2021-04-16T08:35:48.7087750Z 
2021-04-16T08:35:48.7138440Z * Get more help at https://help.gradle.org
2021-04-16T08:35:48.7143830Z 
```
**Area for Triage**:  

Java

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019
- [X] macOS 10.14

**Image version**

20210413.1

**Expected behavior**  
Passing building java on MacOS

**Actual behavior**  
java builds have started failing with 'net.rubygrapefruit.platform.NativeException: Could not query file systems: could not determine file system attributes (errno 5: Input/output error)'

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

Failure Example, https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=359586&view=logs&j=5bc85223-5fed-55e3-d6db-7543b894f171&t=ab98c327-2cb1-5e11-6f8b-ce6abbe034d3

**Comment by gwang-msft** [comment]
Is there any way to downgrade in the pipeline run to using Gradle 6.x?

**Comment by miketimofeev** [comment]
Hi @gwang-msft!
Could you please try the following steps to downgrade gradle in runtime?
```
wget https://services.gradle.org/distributions/gradle-6.8.3-all.zip
unzip gradle-6.8.3-all.zip
ln -sf $(pwd)/gradle-6.8.3/bin/gradle /usr/local/bin/gradle
```

**Comment by gwang-msft** [comment]
@miketimofeev the build passed after adding your steps to downgrade gradle to 6.8.3

**Comment by miketimofeev** [comment]
@gwang-msft good to hear! 
Unfortunately, we can't downgrade the Gradle on the images since our strategy is to install the latest version. Please consider using gradlew to stick to the exact Gradle version for your project https://docs.gradle.org/current/userguide/gradle_wrapper.html
I'm going to close the issue, but feel free to contact us if you have any concerns.
Thank you!

**Comment by gwang-msft** [comment]
@miketimofeev 

I tried Gradle wrapper to use Gradle version 6.8.3

Here is something interesting, even running gradle wrapper will throw the exception, even it will not cause the pipeline to fail, you may want to reconsider downgrade the gradle until it is more stable? Since gradle 7.0 is newly released 7 days ago.

https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=359900&view=logs&j=5bc85223-5fed-55e3-d6db-7543b894f171&t=a7a8be79-50fb-5d0f-16a9-1440a41df19b

https://dev.azure.com/onnxruntime/2a773b67-e88b-4c7f-9fc0-87d31fea8ef2/_apis/build/builds/359900/logs/10
