### ISSUE TITLE
Windows 2019 image create failing

### ISSUE THREAD

**Issue by greadtm** [actions/virtual-environments#4238]
### Description

I am creating a new Azure DevOps VMScaleSet using the image from tag:
win19/20211003.2

I ran into the error in the same location 2 days in a row with above tag.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

win19/20211003.2

### Is it regression?

yes

### Expected behavior

GenerateResourcesandImage task will complete to create windows 2019 image

### Actual behavior

Getting the following exception:
2021-10-06T22:28:45.4991647Z     vhd: Chocolatey installed 3/3 packages.
2021-10-06T22:28:45.5000237Z     vhd:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2021-10-06T22:28:46.5887431Z     vhd: Package installed: wixtoolset|3.11.2
2021-10-06T22:28:46.5899879Z     vhd: Downloading package from: https://wixtoolset.gallerycdn.vsassets.io/extensions/wixtoolset/wixtoolsetvisualstudio2019extension/1.0.0.4/1563296438961/Votive2019.vsix to path C:\Users\packer\AppData\Local\Temp\Votive2019.vsix .
2021-10-06T22:28:47.1365627Z     vhd: Package downloaded successfully in 0.53 seconds
2021-10-06T22:28:47.1373255Z     vhd: Starting Install Votive2019.vsix...
2021-10-06T22:31:30.4503556Z     vhd: Votive2019.vsix installed successfully
2021-10-06T22:31:31.9219122Z     vhd: Pester v5.3.1
2021-10-06T22:31:31.9226783Z     vhd:
2021-10-06T22:31:31.9236307Z     vhd: Starting discovery in 1 files.
2021-10-06T22:31:33.3304399Z     vhd: Discovery found 2 tests in 886ms.
2021-10-06T22:31:33.3311692Z     vhd: Running tests.
2021-10-06T22:31:33.3320225Z     vhd:
2021-10-06T22:31:33.3329639Z     vhd: Running tests from 'C:\image\Tests\Wix.Tests.ps1'
2021-10-06T22:31:35.1731066Z     vhd: Describing Wix
2021-10-06T22:31:36.0204605Z     vhd:   [+] Wix Toolset version from registry 630ms (444ms|185ms)
2021-10-06T22:31:36.0214311Z     vhd:   [+] Wix Toolset version from system 106ms (71ms|35ms)
2021-10-06T22:31:36.8868201Z     vhd: Tests completed in 4.35s
2021-10-06T22:31:36.8875855Z     vhd: Tests Passed: 2, Failed: 0, Skipped: 0 NotRun: 0
2021-10-06T22:31:36.8886081Z ==> vhd: Provisioning with powershell script: D:\VMImage\virtenvwin\images\win/scripts/Installers/Install-WDK.ps1
2021-10-06T22:31:40.9080613Z     vhd: Downloading package from: https://go.microsoft.com/fwlink/?linkid=2166460 to path C:\Users\packer\AppData\Local\Temp\winsdk.iso .
2021-10-06T22:31:41.4404951Z     vhd: Package downloaded successfully in 0.54 seconds
2021-10-06T22:31:42.0198268Z ==> vhd: Mount-DiskImage : The file or directory is corrupted and unreadable.
2021-10-06T22:31:42.0205838Z ==> vhd: At C:\Windows\Temp\script-615e0417-7620-c7e7-2a32-63049e2c4836.ps1:32 char:18
2021-10-06T22:31:42.0214084Z ==> vhd: +     $diskImage = Mount-DiskImage -ImagePath $isoPath
2021-10-06T22:31:42.0224556Z ==> vhd: +                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-10-06T22:31:42.0236583Z ==> vhd:     + CategoryInfo          : NotSpecified: (MSFT_DiskImage:ROOT/Microsoft/.../MSFT_DiskImage) [Mount-DiskImage], CimE
2021-10-06T22:31:42.0243679Z ==> vhd:    xception
2021-10-06T22:31:42.0254829Z ==> vhd:     + FullyQualifiedErrorId : HRESULT 0x80070570,Mount-DiskImage
2021-10-06T22:31:42.0264152Z ==> vhd:
2021-10-06T22:31:42.0277196Z ==> vhd: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
2021-10-06T22:31:42.0279946Z ==> vhd: Step "StepProvision" failed
2021-10-07T13:08:20.7316274Z ##[debug]Re-evaluate condition on job cancellation for step: 'Azure PowerShell script: FilePath'.
2021-10-07T13:08:20.7453530Z ==> vhd: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? 
2021-10-07T13:08:20.7454444Z Cancelling build after receiving interrupt
2021-10-07T13:08:20.7493236Z ==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present...
2021-10-07T13:08:20.7575769Z ==> vhd: Removing the created Deployment object: 'pkrdp2vhe6dx4j9'
2021-10-07T13:08:31.0077056Z ##[error]The operation was canceled.
2021-10-07T13:08:31.0096801Z ##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2021-10-07T13:08:31.0103313Z ##[section]Finishing: Azure PowerShell script: FilePath

### Repro steps

Import-Module .\helpers\GenerateResourcesAndImage.ps1

GenerateResourcesAndImage -SubscriptionId $subscriptionId -ResourceGroupName $rgname -ImageGenerationRepositoryRoot "$pwd" -ImageType windows2019 -AzureLocation "eastus2" -AzureTenantId $AzureTenantID -AzureClientId $AzureClientID -AzureClientSecret $AzureClientSecret

Variable values are obfuscated.

We have been successfully running this process for a few months now.

**Comment by greadtm** [comment]
I will try again with centralus.

**Comment by greadtm** [comment]
I ran into the same error with centralus region as the image source.

**Comment by greadtm** [comment]
I am just trying to educate myself on the process. If Main is considered stable and released version, I will give it a try.
