### ISSUE TITLE
macOS: `brew cask install virtualbox` fails (probably due to the kext issue)

### ISSUE THREAD

**Issue by AkihiroSuda** [actions/virtual-environments#429]
**Describe the bug**
`brew cask install virtualbox` fails

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [X] macOS 10.15

**Expected behavior**
`brew cask install virtualbox`  should succeed.
Ideally it should be installed by default.

**Actual behavior**
yaml:
```yaml
name: foo
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - run: brew cask install virtualbox
```

log:

```
2020-02-20T04:04:16.4213269Z ##[section]Starting: Request a runner to run this job
2020-02-20T04:04:16.7145011Z Requesting a hosted runner in current repository's account/organization with labels: 'macos-latest', require runner match: True
2020-02-20T04:04:16.8709239Z Labels matched hosted runners has been found, waiting for one of them get assigned for this job.
2020-02-20T04:04:16.9065891Z ##[section]Finishing: Request a runner to run this job
2020-02-20T04:04:33.7751230Z Current runner version: '2.165.2'
2020-02-20T04:04:33.7752600Z Prepare workflow directory
2020-02-20T04:04:33.8599150Z Prepare all required actions
2020-02-20T04:04:33.9791800Z ##[group]Run uname -a
2020-02-20T04:04:33.9792270Z [36;1muname -a[0m
2020-02-20T04:04:34.2328130Z shell: /bin/bash -e {0}
2020-02-20T04:04:34.2328540Z ##[endgroup]
2020-02-20T04:04:34.2692910Z Darwin Mac-1313.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
2020-02-20T04:04:34.2983360Z ##[group]Run brew cask install virtualbox
2020-02-20T04:04:34.2983690Z [36;1mbrew cask install virtualbox[0m
2020-02-20T04:04:34.3120490Z shell: /bin/bash -e {0}
2020-02-20T04:04:34.3121120Z ##[endgroup]
2020-02-20T04:04:42.5394490Z ==> Caveats
2020-02-20T04:04:42.5396050Z To install and/or use virtualbox you may need to enable its kernel extension in:
2020-02-20T04:04:42.5403790Z   System Preferences 竊� Security & Privacy 竊� General
2020-02-20T04:04:42.5408150Z For more information refer to vendor documentation or this Apple Technical Note:
2020-02-20T04:04:42.5410150Z   https://developer.apple.com/library/content/technotes/tn2459/_index.html
2020-02-20T04:04:42.5411850Z 
2020-02-20T04:04:42.6162040Z ==> Downloading https://download.virtualbox.org/virtualbox/6.1.2/VirtualBox-6.1.2-135662-OSX.dmg
2020-02-20T04:04:49.3507080Z ==> Verifying SHA-256 checksum for Cask 'virtualbox'.
2020-02-20T04:04:50.6102940Z ==> Installing Cask virtualbox
2020-02-20T04:05:09.9505060Z ==> Running installer for virtualbox; your password may be necessary.
2020-02-20T04:05:09.9506980Z ==> Package installers may write to any location; options such as --appdir are ignored.
2020-02-20T04:05:17.8446560Z Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=runner USER=runner USERNAME=runner /usr/sbin/installer -pkg /usr/local/Caskroom/virtualbox/6.1.2,135662/VirtualBox.pkg -target / -applyChoiceChangesXML /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/choices20200220-1671-1smh716.xml` exited with 1. Here's the output:
2020-02-20T04:05:17.8449970Z installer: Package name is Oracle VM VirtualBox
2020-02-20T04:05:17.8451060Z installer: choices changes file '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/choices20200220-1671-1smh716.xml' applied
2020-02-20T04:05:17.8451590Z installer: Installing at base path /
2020-02-20T04:05:17.8452740Z installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package 窶弖irtualBox.pkg窶�.)
2020-02-20T04:05:17.8453180Z Follow the instructions here:
2020-02-20T04:05:17.8453920Z   https://github.com/Homebrew/homebrew-cask#reporting-bugs
2020-02-20T04:05:17.8454650Z /usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
2020-02-20T04:05:17.8455350Z /usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
2020-02-20T04:05:17.8455980Z /usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
2020-02-20T04:05:17.8456640Z /usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
2020-02-20T04:05:17.8457340Z /usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:59:in `block in run_installer'
2020-02-20T04:05:17.8458010Z /usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:70:in `block in with_choices_file'
2020-02-20T04:05:17.8458650Z /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
2020-02-20T04:05:17.8459410Z /usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:67:in `with_choices_file'
2020-02-20T04:05:17.8460020Z /usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:52:in `run_installer'
2020-02-20T04:05:17.8460700Z /usr/local/Homebrew/Library/Homebrew/cask/artifact/pkg.rb:34:in `install_phase'
2020-02-20T04:05:17.8461880Z /usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
2020-02-20T04:05:17.8462660Z /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
2020-02-20T04:05:17.8464110Z /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
2020-02-20T04:05:17.8465600Z /usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
2020-02-20T04:05:17.8466150Z /usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
2020-02-20T04:05:17.8466660Z /usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
2020-02-20T04:05:17.8467670Z /usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
2020-02-20T04:05:17.8468280Z /usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
2020-02-20T04:05:17.8468800Z /usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
2020-02-20T04:05:17.8469280Z /usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
2020-02-20T04:05:17.8469780Z /usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
2020-02-20T04:05:17.8470220Z /usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
2020-02-20T04:05:17.8470820Z /usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
2020-02-20T04:05:17.8471300Z /usr/local/Homebrew/Library/Homebrew/brew.rb:103:in `<main>'
2020-02-20T04:05:17.8472660Z installer: Package name is Oracle VM VirtualBox
2020-02-20T04:05:17.8479130Z installer: choices changes file '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/choices20200220-1671-1smh716.xml' applied
2020-02-20T04:05:17.8482050Z installer: Installing at base path /
2020-02-20T04:05:17.8483280Z installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package 窶弖irtualBox.pkg窶�.)
2020-02-20T04:05:17.8483520Z ==> Purging files for version 6.1.2,135662 of Cask virtualbox
2020-02-20T04:05:17.8496580Z ##[error]Process completed with exit code 1.
2020-02-20T04:05:17.8599480Z Cleaning up orphan processes
```

Probably due to a kext issue (https://developer.apple.com/library/archive/technotes/tn2459/_index.html)

**Comment by vmapetr** [comment]
Hi @AkihiroSuda! Thanks for reporting this issue. Indeed, Virtualbox installation is failing due to kext user consent restrictions. Unfortunately we can't provide workaround for kext due to enabled SIP on macOS images. 
Can you, please create new issue (or change description in current) about adding preinstalled Virtualbox on macOS images?

**Comment by AkihiroSuda** [comment]
Sure: https://github.com/actions/virtual-environments/issues/433
