### ISSUE TITLE
Update of Azure CLI 2.28.0 -> 2.29.0 is broken

### ISSUE THREAD

**Issue by b10-dslappendel** [actions/virtual-environments#4327]
### Description

On Azure DevOps, we've noticed that yesterday an update of the Windows 2022 image was deployed, which includes the update of Azure CLI from 2.28.0 to 2.29.0.

With this update, one of our scripts that uses the `az webapp show --name <any_name> --query 'id'` command, fails.

Now there [seems to be an update to 2.29.1](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli) which suggests that these webapp commands have been fixed.

We would appreciate it if Azure CLI can be updated to 2.29.1 (if that version works, I actually have no clue) or reverted back to 2.28.0 as a hotfix. Thank you for your time.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20211018.0

### Is it regression?

20211011.0

### Expected behavior

The command `az webapp show --name <any_name> --query 'id'` should not fail.

### Actual behavior

The command `az webapp show --name <any_name> --query 'id'` fails with the following message:

```log
2021-10-21T12:32:19.4761960Z ERROR: The command failed with an unexpected error. Here is the traceback:
2021-10-21T12:32:19.4765207Z ERROR: 'str' object has no attribute 'value'
2021-10-21T12:32:19.4766488Z Traceback (most recent call last):
2021-10-21T12:32:19.4767312Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
2021-10-21T12:32:19.4768724Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 657, in execute
2021-10-21T12:32:19.4769455Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
2021-10-21T12:32:19.4770119Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 691, in _run_job
2021-10-21T12:32:19.4770792Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
2021-10-21T12:32:19.4771471Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 363, in handler
2021-10-21T12:32:19.4772102Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/arm.py", line 429, in show_exception_handler
2021-10-21T12:32:19.4772749Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 361, in handler
2021-10-21T12:32:19.4773402Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 607, in show_webapp
2021-10-21T12:32:19.4774042Z   File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 736, in _show_app
```

### Repro steps

1. Create an Azure DevOps deployment pipeline
2. Create a new Azure CLI step
3. Include the command `az webapp show --name <any_name> --query 'id'` (with `<any_name>` replaced with an actual Azure resource)
4. Run the deployment

**Comment by b10-dslappendel** [comment]
@al-cheb Sadly as I've mentioned in the linked issue Azure/azure-cli#20049, this is not fixed with Azure CLI 2.30.0.
