### ISSUE TITLE
SQL Server error in image 20220110.1 "Failed to initialize the Common Language Runtime (CLR) v4.0.30319 with HRESULT 0x80004005. You need to restart SQL Server to use CLR integration features."

### ISSUE THREAD

**Issue by buckleyGI** [actions/virtual-environments#4879]
### Description

Hi,

We are getting 100% build failures in our tests that use sql server as of image version 20220110.1
A minority of the agents we get are still on 20211219.1 and their the test work 100%
So this bump in image version deterministically breaking our tests

The error we get is
`Failed to initialize the Common Language Runtime (CLR) v4.0.30319 with HRESULT 0x80004005. You need to restart SQL Server to use CLR integration features.`

Comparing the image version 
https://github.com/actions/virtual-environments/blob/win19/20211219.1/images/win/Windows2019-Readme.md
https://github.com/actions/virtual-environments/blob/win19/20220110.1/images/win/Windows2019-Readme.md
does not bring to light what update could have cause this

When we look at solutions for this error we see a recurring advice to Repairing the .NET Framework.
eg. https://dba.stackexchange.com/questions/202250/how-to-solve-the-failed-to-initialize-the-clr/202258

Could it be that a corruption for sql server slipped into this image?

Thank you

Redacted version of stack trace:

```
2022-01-13T11:20:40.2723643Z   Error Message:
2022-01-13T11:20:40.2768630Z    System.Data.SqlClient.SqlException : Failed to initialize the Common Language Runtime (CLR) v4.0.30319 with HRESULT 0x80004005. You need to restart SQL Server to use CLR integration features.
2022-01-13T11:20:40.2773550Z The statement has been terminated.
2022-01-13T11:20:40.2776070Z Data:
2022-01-13T11:20:40.2777067Z   HelpLink.ProdName: Microsoft SQL Server
2022-01-13T11:20:40.2777951Z   HelpLink.ProdVer: 13.00.4001
2022-01-13T11:20:40.2779162Z   HelpLink.EvtSrc: MSSQLServer
2022-01-13T11:20:40.2782890Z   HelpLink.BaseHelpUrl: http://go.microsoft.com/fwlink
2022-01-13T11:20:40.2781944Z   HelpLink.EvtID: 6512
2022-01-13T11:20:40.2783825Z   HelpLink.LinkId: 20476
2022-01-13T11:20:40.2784743Z   Stack Trace:
2022-01-13T11:20:40.2785796Z      at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2022-01-13T11:20:40.2787123Z    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
2022-01-13T11:20:40.2788391Z    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
2022-01-13T11:20:40.2791988Z    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
2022-01-13T11:20:40.2794545Z    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
2022-01-13T11:20:40.2796802Z    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
2022-01-13T11:20:40.2798642Z    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
2022-01-13T11:20:40.2800258Z    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
2022-01-13T11:20:40.2801744Z    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
2022-01-13T11:20:40.2802634Z    at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2813
2022-01-13T11:20:40.2804893Z    at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 572
2022-01-13T11:20:40.2806108Z    at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 443
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

fail    image version: '20220110.1' 
https://dev.azure.com/selligentsim/ES/_build/results?buildId=359908&view=logs&j=9a886eec-a62e-5a78-e411-1218123ab3c3&t=e3b90326-37af-5341-db04-6fdf17db0c49

success image version: '20211219.1'
https://dev.azure.com/selligentsim/ES/_build/results?buildId=359874&view=logs&j=9a886eec-a62e-5a78-e411-1218123ab3c3&t=e3b90326-37af-5341-db04-6fdf17db0c49

### Repro steps

Use sql server from image version 20220110.1

**Comment by al-cheb** [comment]
Hey @buckleyGI,
Do you have a simple repo to reproduce the issue?

**Comment by buckleyGI** [comment]
Hi @al-cheb 
Not ATM. My guess it will be a bit of work to write a minimal repro and we are currently looking to mitigate the issue.
Is there a way to pin/force exuction to and older image?
Thank you!

**Comment by buckleyGI** [comment]
When we specify windows-2022 instead of windows-2019 we get the older image so are saved by this workaround.
Do, don't release the new image for 2022 please :)

**Comment by dsame** [comment]
@buckleyGI i do not have an access to the builds. Is it possible to see the pipelines?

**Comment by dsame** [comment]
> @dsame Can we can send the logs and the fully expanded yaml pipeline to an internal address?

yes, send them to my github email, please

**Comment by buckleyGI** [comment]
@dsame You should have received the redacted logs. Thanks for the follow up!

**Comment by dsame** [comment]
@buckleyGI i've got the logs and see no mssql initialisation code in YAML file.

I suppose you create clean mssql instance for the unit tests and in this case can you please provide:

1. A fragment of code to install mssql db endgine
2. A fragment of code to enable CLR integration
3. A fragment of code to create CLR assembly (i do not need assembly code itself)
4. A fragment of code to use user defined function from the assembly

I need these fragments in order to reproduce the problem in case if the mssql instance is initialised by the code on NUnitTests. 

In case If the mssql database is maintained outside of the code and there's no the fragments please contact your administrator. 

In any case i advise you to double check the precense of 
```
RECONFIGURE  
GO  
```
after `sp_configure 'clr enabled', 1  ` and before the first use of CLR UDF.

**Comment by buckleyGI** [comment]
@dsame I sent you the redacted code fragments

**Comment by buckleyGI** [comment]
It seems we got lucky though. The second image that caused the failures did not get a server 2022 release (duno why)

2021 12 19.1 20211219.1 success
2022 01 10.1 20220110.1 fail
2022 01 16.1 20220116.1 success <= current 2022

An we are currently already running on the image after that (3th in the list) and this one doesn't cause the problems

We dodged the bullet possibly.

**Comment by miketimofeev** [comment]
@buckleyGI I'm going to close the issue. Please feel free to contact us if the problem appears again and we will continue the investigation.
Thank you!

**Comment by buckleyGI** [comment]
Will do. Thanks for the invesigation so far Sergey 🙇
