### ISSUE TITLE
Tests on windows-latest (2019) no longer allowed to kill processes?

### ISSUE THREAD

**Issue by djc** [actions/virtual-environments#5060]
### Description

In https://github.com/rustls/hyper-rustls/runs/5098841616?check_suite_focus=true, windows-latest jobs started failing like this:

```
 ---- custom_ca_store stdout ----
thread 'custom_ca_store' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', tests\tests.rs:53:16
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\core\src\panicking.rs:107
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\core\src\result.rs:1613
   3: enum$<core::result::Result<tuple$<>,std::io::error::Error>, 0, 3, Err>::unwrap<tuple$<>,std::io::error::Error>
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\core\src\result.rs:1295
   4: tests::custom_ca_store
             at .\tests\tests.rs:53
   5: tests::custom_ca_store::closure$0
             at .\tests\tests.rs:39
   6: core::ops::function::FnOnce::call_once<tests::custom_ca_store::closure$0,tuple$<> >
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\core\src\ops\function.rs:227
   7: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The line at `tests.rs:53` is `srv.kill().unwrap();`, where `srv` is a [`Child`](https://doc.rust-lang.org/std/process/struct.Child.html) process, calling the [`kill`](https://doc.rust-lang.org/std/process/struct.Child.html#method.kill) method.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.287.1'
Operating System
  Microsoft Windows Server 2019
  10.0.17763
  Datacenter
Virtual Environment
  Environment: windows-2019
  Version: 20220131.1
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20220131.1/images/win/Windows2019-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20220131.1
Virtual Environment Provisioner
  1.0.0.0-main-20220128-1

### Is it regression?

Yes, succeeded in https://github.com/rustls/hyper-rustls/runs/4695816351?check_suite_focus=true (runner 2.285.1, windows-2019 20211219.1)

### Expected behavior

Child process gets killed.

### Actual behavior

Process kill is permission denied (OS error code 5).

### Repro steps

Run a job that kills a child process.

**Comment by al-cheb** [comment]
Hello @djc ,
We will take a look at it.

**Comment by nikolai-frolov** [comment]
Hello @djc, could you please try to set `test-threads 1` since this error can be a result of race condition?
```
run: cargo test --verbose --test-threads 1
```
In case it doesn't work for you, please provide a simple project where the issue is reproducible.

**Comment by nikolai-frolov** [comment]
Closing issue since there is no activity. Feel free to reopen in case issue is still actual.
