### ISSUE TITLE
ubuntu 20.04 virtual environment build fails while configuring .NET 6.0

### ISSUE THREAD

**Issue by rybal06** [actions/virtual-environments#5197]
### Description

When attempting to build an image using the contents of this repository, this error occurs:

```bash
azure-arm: Installing dotnet tool nbgv
    azure-arm:
    azure-arm: Welcome to .NET 6.0!
    azure-arm: ---------------------
    azure-arm: SDK Version: 6.0.200
    azure-arm:
    azure-arm: ----------------
    azure-arm: Installed an ASP.NET Core HTTPS development certificate.
    azure-arm: To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
    azure-arm: Learn about HTTPS: https://aka.ms/dotnet-https
    azure-arm: ----------------
    azure-arm: Write your first app: https://aka.ms/dotnet-hello-world
    azure-arm: Find out what's new: https://aka.ms/dotnet-whats-new
    azure-arm: Explore documentation: https://aka.ms/dotnet-docs
    azure-arm: Report issues and find source on GitHub: https://github.com/dotnet/core
    azure-arm: Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli[](https://aka.ms/failure-installing-tool)
    azure-arm: --------------------------------------------------------------------------------------
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242: SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk". Exception: "System.IO.DirectoryNotFoundException: Could not find a part of the path '/usr/share/dotnet/sdk-manifests'.
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242:    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242:    at System.IO.Enumeration.FileSystemEnumerator`1.Init()
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242:    at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242:    at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242:    at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242:    at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242:    at System.IO.Directory.GetDirectories(String path, String searchPattern, EnumerationOptions enumerationOptions)
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242:    at System.IO.Directory.GetDirectories(String path)
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.FallbackForMissingManifest(String manifestId)
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.GetManifestDirectories()
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.GetManifests()+MoveNext()
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.LoadManifestsFromProvider(IWorkloadManifestProvider manifestProvider)
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir)
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242:    at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir)
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242:    at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.WorkloadSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
    azure-arm: /tmp/kzqideat.uk2/restore.csproj(5,31): error MSB4242:    at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)""
==> azure-arm: The tool package could not be restored.
==> azure-arm: Tool 'nbgv' failed to install. This failure may have been caused by:
==> azure-arm:
==> azure-arm: * You are attempting to install a preview release and did not use the --version option to specify the version.

    azure-arm: Containers            : {[-] /imagegeneration/tests/DotnetSDK.Tests.ps1}
    azure-arm: Result                : Failed
    azure-arm: FailedCount           : 1
    azure-arm: FailedBlocksCount     : 0
    azure-arm: FailedContainersCount : 0
    azure-arm: PassedCount           : 7
    azure-arm: SkippedCount          : 0
    azure-arm: NotRunCount           : 0
    azure-arm: TotalCount            : 8
    azure-arm: Duration              : 00:00:01.0650103
    azure-arm: Executed              : True
    azure-arm: ExecutedAt            : 03/08/2022 18:20:13
    azure-arm: Version               : 5.3.1
    azure-arm: PSVersion             : 7.2.1
    azure-arm: PSBoundParameters     : {[Configuration, PesterConfiguration]}
    azure-arm: Plugins               : 
    azure-arm: PluginConfiguration   : 
    azure-arm: PluginData            : 
    azure-arm: Configuration         : PesterConfiguration
    azure-arm: DiscoveryDuration     : 00:00:00.2498095
    azure-arm: UserDuration          : 00:00:00.3311239
    azure-arm: FrameworkDuration     : 00:00:00.4840769
    azure-arm: Failed                : {[-] nbgv is available}
    azure-arm: FailedBlocks          : {}
    azure-arm: FailedContainers      : {}
    azure-arm: Passed                : {[+] Default Dotnet SDK is available, [+] SDK 3.1 is av
    azure-arm:                         ailable, [+] Runtime 3.1 is available, [+] SDK 5.0 is a
    azure-arm:                         vailable…}
    azure-arm: Skipped               : {}
    azure-arm: NotRun                : {}
    azure-arm: Tests                 : {[+] Default Dotnet SDK is available, [+] SDK 3.1 is av
    azure-arm:                         ailable, [+] Runtime 3.1 is available, [+] SDK 5.0 is a
    azure-arm:                         vailable…}
    azure-arm: CodeCoverage          : 
    azure-arm:
==> azure-arm: Exception: Test run has failed
==> azure-arm: 
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220306.1 https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md

### Repro steps

1. Configure azure devops yaml pipeline using the contents of the 'main' branch of this repository.
2. Configure the pipeline to run on 'ubuntu-latest' agent pool.
3. Observe error message during build and failure.

This last worked to build 20220207.1 on 02/17/2022.

**Comment by rybal06** [comment]
Upon second attempt, the repository worked. It is possible this is an intermittent issue, perhaps a timing issue with the packer image build? I will attempt once more before closing this.

**Comment by rybal06** [comment]
This built successfully twice after the failure with no code changes, closing the issue.

**Comment by mgrosen** [comment]
Hey, thanks for reporting this! There was indeed an issue with 20220306.1, we rolled back 90% of updated Ubuntu 20.04 runners yesterday, and finished rolling back to 20220207.1  everywhere today.
