### ISSUE TITLE
Android project unit tests failing

### ISSUE THREAD

**Issue by shavinda-2022** [actions/virtual-environments#5347]
### Description

Since 04/04/2022 unit tests that pass on my local machine are failing when executed via Github Actions.

The date tallies up roughly with when the ubuntu-20.04 image was updated.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Unit tests fails
-   Environment: ubuntu-20.04
-   Version: 20220330.0
-   Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220330.0/images/linux/Ubuntu2004-Readme.md
-   Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220330.0

Last test pass version:
  Environment: ubuntu-20.04
  Version: 20220227.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220227.1/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220227.1

Tests Also Pass on macos runner:
Environment: macos-11
  Version: 20220322.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20220322.1/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-[11](https://github.com/santander-group-uk/firefly-android/runs/5832008077?check_suite_focus=true#step:1:11)%2F20220322.1

### Is it regression?

20220227.1

### Expected behavior

Unit tests to pass on ubuntu runner

### Actual behavior

Unit tests to fail on the latest image of ubuntu-20.04 runner, when the same codebase passes on macos-11.

Since this is an Android project ubuntu vs macos should NOT make a difference.

### Repro steps

The failing project is private and hence I am not able to share links.

The test failures are at random locations, but the following stacktrace is usually generated from the logs.

```
> Task :app:testDevDebugUnitTest
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at io.mockk.proxy.jvm.advice.BaseAdvice.handle(BaseAdvice.kt:42)
	at io.mockk.proxy.jvm.advice.jvm.JvmMockKProxyInterceptor.interceptNoSuper(JvmMockKProxyInterceptor.java:45)
	at android.content.Context$Subclass10.getApplicationContext(Unknown Source)
	at com.adobe.mobile.MobileConfig.startNotifier(MobileConfig.java:1234)
	at com.adobe.mobile.MobileConfig.<init>(MobileConfig.java:183)
	at com.adobe.mobile.MobileConfig.getInstance(MobileConfig.java:170)
	at com.adobe.mobile.RequestBuilder.buildAndSendRequest(RequestBuilder.java:53)
	at com.adobe.mobile.AnalyticsTrackState.trackState(AnalyticsTrackState.java:30)
	at com.adobe.mobile.Analytics$1.run(Analytics.java:71)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Error: Exception in thread "pool-2-thread-3" io.mockk.MockKException: no answer found for: Context(context#2321).getPackageManager()
	at io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:90)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:42)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:263)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at io.mockk.proxy.jvm.advice.BaseAdvice.handle(BaseAdvice.kt:42)
	at io.mockk.proxy.jvm.advice.jvm.JvmMockKProxyInterceptor.interceptNoSuper(JvmMockKProxyInterceptor.java:45)
	at android.content.Context$Subclass10.getPackageManager(Unknown Source)
	at com.adobe.mobile.StaticMethods.getApplicationName(StaticMethods.java:240)
	at com.adobe.mobile.StaticMethods.getApplicationID(StaticMethods.java:216)
	at com.adobe.mobile.AnalyticsTrackAction.trackAction(AnalyticsTrackAction.java:36)
	at com.adobe.mobile.Analytics$2.run(Analytics.java:81)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by al-cheb** [comment]
Hello @shavinda-2022,
Please provide a small repo how to reproduce the issue.

**Comment by shavinda-2022** [comment]
@al-cheb I'm working on setting up a simple project, I can't seem to identify what exactly causes the failures.
The failing project is a big project. So identifying the exact component might be problematic. Need some time to isolate the components that could cause the failure.

**Comment by reshadf** [comment]
we have the same issue starting 2 days ago. The only thing that we noticed was also an updated image version. the error that we get however, is as follows: 

`Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Test worker"`

**Comment by miketimofeev** [comment]
@shavinda-2022 feel free to reopen when you have a reproducible example, otherwise, I'm afraid, we can't help you.
