### ISSUE TITLE
Bundler version included in macOS 11 20220501.1 doesn't match readme

### ISSUE THREAD

**Issue by gianlucapisati** [actions/virtual-environments#5525]
### Description

The readme of macOS 11 20220501.1 says that Bundler version is 2.3.12 but 
`bundler --version` inside the virtual machine says it's 2.2.33

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220501.1

### Expected behavior

Bundler version should be the one reported in the readme, 2.3.12

### Actual behavior

bundler --version outputs 2.2.33

### Repro steps

1. launch macOS 11 20220501.1 VM
2. execute a bash script with bundler --version

**Comment by miketimofeev** [comment]
Hi @gianlucapisati!
Could you share your workflow as `bundler --version` gives me the expected result
```
Bundler version 2.3.13
```

**Comment by gianlucapisati** [comment]
HI @miketimofeev, thanks for the prompt reply.

I hope this screenshots helps you understanding my setup

Pipeline configuration:
<img width="1440" alt="1" src="https://user-images.githubusercontent.com/438602/167915881-e9b429c1-6875-4030-8a42-da17a96e30b3.png">

Agent specification:
<img width="1438" alt="2" src="https://user-images.githubusercontent.com/438602/167915885-b63e7d09-0dd3-4d7d-95ca-7bbbd66717c4.png">

Job initialization:
<img width="1440" alt="3" src="https://user-images.githubusercontent.com/438602/167915891-88075ea4-e7c0-4154-a7bc-ea5b5be0e8f5.png">

Bundler version step:
<img width="1440" alt="4" src="https://user-images.githubusercontent.com/438602/167915893-ac7ce47f-0a77-49ba-a4ea-688029a4fdd2.png">

**Comment by al-cheb** [comment]
@gianlucapisati, Could you provide `which -a bundler` output?

**Comment by gianlucapisati** [comment]
@al-cheb, sure, here it is:

```
$which -a bundler
/usr/local/lib/ruby/gems/2.7.0/bin/bundler
/usr/local/opt/ruby@2.7/bin/bundler
/usr/bin/bundler
```

**Comment by al-cheb** [comment]
@gianlucapisati , What's the output for each one?

```
echo "#1"
/usr/local/lib/ruby/gems/2.7.0/bin/bundler --version
echo "#2"
/usr/local/opt/ruby@2.7/bin/bundler --version
echo "#3"
/usr/bin/bundler --version
```

**Comment by gianlucapisati** [comment]
@al-cheb, here it is:

```
2022-05-12T08:50:07.2614170Z [command]/bin/bash /Users/runner/work/_temp/ce3bb833-6e55-4d39-93e9-e669dd795d0d.sh
2022-05-12T08:50:07.2704850Z #1
2022-05-12T08:50:07.9915770Z Bundler version 2.2.33
2022-05-12T08:50:07.9938310Z #2
2022-05-12T08:50:08.2797050Z Bundler version 2.2.33
2022-05-12T08:50:08.2819310Z #3
2022-05-12T08:50:11.3363260Z /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.3.11) required by your /Users/runner/work/1/s/Gemfile.lock. (Gem::GemNotFoundException)
2022-05-12T08:50:11.3365740Z To update to the latest version installed on your system, run `bundle update --bundler`.
2022-05-12T08:50:11.3366540Z To install the missing version, run `gem install bundler:2.3.11`
2022-05-12T08:50:11.3368090Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
2022-05-12T08:50:11.3369190Z 	from /usr/bin/bundler:23:in `<main>'
2022-05-12T08:50:11.3463660Z ##[error]Bash exited with code '1'.
2022-05-12T08:50:11.3512390Z ##[section]Finishing: Bundler version
```

**Comment by al-cheb** [comment]
@gianlucapisati,  `cd ~ && bundler --version`, looks like Gemfile.lock file lock the version of bundler.

**Comment by gianlucapisati** [comment]
@al-cheb yes you are right, it was my problem, sorry if I wasted your time 😅
