### ISSUE TITLE
[Windows] Recent update to windows-latest image broke Python calls

### ISSUE THREAD

**Issue by nickymarino** [actions/virtual-environments#5683]
### Description

A GitHub action that runs Python tests (via pytests) ran successfully on May 20 2022, but it failed today when I re-ran the job (exact same commit, exact same action, exact same code, etc.)

See [this set of runs](https://github.com/Thoughtful-Automation/supervisor/runs/6612653895?check_suite_focus=true#step:7:109) for my repo. Run [#1](https://support.github.com/ticket/1) ran successfully, but when I clicked re-run job it failed. Nothing has changed: it's the same commit running the same workflow (the workflows have not been changed after the successful run on May 20 2022).

I found evidence that the [recent update](https://github.com/actions/virtual-environments/releases/tag/win22%2F20220515.1) to the windows-latest broke something in that image's Python install.

Background: Our action passed 7 days ago and failed 1 day ago, even though it were running the exact same commit. (The failed action run was a re-run of the passing run)

Timeline:

11 days ago there was an [update to windows-latest](https://github.com/actions/virtual-environments/releases/tag/win22%2F20220515.1) that didn’t modify Python, and our action passed 4 days after that update
There was [another update to windows-latest](https://github.com/actions/virtual-environments/releases/tag/win22%2F20220515.1) 3 days ago in the middle of the two test runs (success may 20, failure may 26) that updated the Python install, and our action failed 2 days after that update.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Environment: windows-2022
Version: 20220515.1
Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20220515.1
Virtual Environment Provisioner: 1.0.0.0-main-20220421-1

### Is it regression?

Yes. Latest working version is windows-2022 20220515.1 and working run: https://github.com/Thoughtful-Automation/supervisor/runs/6531383576?check_suite_focus=true

### Expected behavior

The run should have succeeded, like this previous run of the same workflow and same commit: https://github.com/Thoughtful-Automation/supervisor/runs/6531383576?check_suite_focus=true

### Actual behavior

[Full logs are here](https://pipelines.actions.githubusercontent.com/serviceHosts/399264f1-f43c-4652-9425-7b30c3608c3b/_apis/pipelines/1/runs/498/signedlogcontent/4?urlExpires=2022-05-26T18%3A26%3A18.3673983Z&urlSigningMethod=HMACV1&urlSignature=DM2E%2BYRbbRsoAhGEZMbmdoVf%2FdV4R6x411K%2Fzah6xx8%3D) for the job.

In particular, python.exe seems to be missing:

```
2022-05-26T16:11:59.4797628Z poetry run pytest -vv --cov=supervisor/ --cov-report term-missing --cov-config .coveragerc 
2022-05-26T16:12:00.7196530Z 
2022-05-26T16:12:00.7244830Z   EnvCommandError
2022-05-26T16:12:00.7245230Z 
2022-05-26T16:12:00.7246038Z   Command D:\a\supervisor\supervisor\.venv\Scripts\python.exe -W ignore - errored with the following return code 103, and output: 
2022-05-26T16:12:00.7247615Z   No Python at 'C:\hostedtoolcache\windows\Python\3.9.12\x64\python.exe'
2022-05-26T16:12:00.7248020Z 
2022-05-26T16:12:00.7248226Z   input was : import sys
2022-05-26T16:12:00.7248606Z   
2022-05-26T16:12:00.7248927Z   if hasattr(sys, "real_prefix"):
2022-05-26T16:12:00.7249279Z       print(sys.real_prefix)
2022-05-26T16:12:00.7249630Z   elif hasattr(sys, "base_prefix"):
2022-05-26T16:12:00.7249982Z       print(sys.base_prefix)
2022-05-26T16:12:00.7250296Z   else:
2022-05-26T16:12:00.7250599Z       print(sys.prefix)
2022-05-26T16:12:00.7250903Z   
2022-05-26T16:12:00.7251110Z 
2022-05-26T16:12:00.7251964Z   at ~\AppData\Roaming\Python\Scripts\venv\lib\site-packages\poetry\utils\env.py:1183 in _run
2022-05-26T16:12:00.8820056Z Traceback (most recent call last):
2022-05-26T16:12:00.8830117Z   File "C:\Users\runneradmin\AppData\Roaming\Python\Scripts\venv\lib\site-packages\poetry\utils\env.py", line 1168, in _run
2022-05-26T16:12:00.8831608Z     output = subprocess.run(
2022-05-26T16:12:00.8832931Z   File "C:\Users\runneradmin\AppData\Roaming\Python\Scripts\venv\lib\site-packages\poetry\utils\_compat.py", line 217, in run
2022-05-26T16:12:00.8834605Z     raise CalledProcessError(
2022-05-26T16:12:00.8835465Z poetry.utils._compat.CalledProcessError: Command 'D:\a\supervisor\supervisor\.venv\Scripts\python.exe -W ignore -' returned non-zero exit status 103.
```

### Repro steps

Reproduction Steps

Rerun [this workflow](https://github.com/Thoughtful-Automation/supervisor/runs/6612653895?check_suite_focus=true#step:7:109) and the job will fail, even though run [#1](https://support.github.com/ticket/1) was successful with the same code/actions.

**Comment by al-cheb** [comment]
There is no Python 3.9.12 it was updated to Python 3.9.13 -https://github.com/actions/setup-python . This is by design behavior because you built poetry cache with old Python version. You should rebuild poetry cache with any available Python versions on the image. Please ask question about it  - https://github.com/actions/setup-python
