### ISSUE TITLE
Win2019 execution fails while downloading the package

### ISSUE THREAD

**Issue by celenn** [actions/virtual-environments#5733]
### Description

Its for windows 2019 deployment and it was working fine earlier but the build has been failing for the last 4 attempt as PS exited with 1. 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Powershell exited with code 1.

### Is it regression?

no

### Expected behavior

Installation success and continue execution

### Actual behavior

2022-06-13T23:10:57.7689492Z ==> vhd: Machine successfully restarted, moving on
2022-06-13T23:10:57.7717080Z ==> vhd: Provisioning with Powershell...
2022-06-13T23:10:57.7733255Z ==> vhd: Provisioning with powershell script: C:\a\1\s\virtual-environments\images\win/scripts/Installers/Install-VS.ps1
2022-06-13T23:11:11.3248304Z     vhd: Downloading Bootstrapper ...
2022-06-13T23:11:11.3268697Z     vhd: Downloading package from: https://aka.ms/vs/16/release/vs_Enterprise.exe to path C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe .
2022-06-13T23:11:11.3289423Z     vhd: Package downloaded successfully in 0.19 seconds
2022-06-13T23:11:11.3315705Z     vhd: Enable short name support on Windows needed for Xamarin Android AOT, defaults appear to have been changed in Azure VMs
2022-06-13T23:11:12.6377683Z     vhd: Starting Install ...
2022-06-13T23:12:52.2094985Z     vhd: [1b4c:00a2][2022-06-13T23:12:31] Package 'Microsoft.VC.14.29.16.11.Premium.Tools.HostX86.TargetX86.base,version=14.29.30142' failed to download from 'https://download.visualstudio.microsoft.com/download/pr/f0356831-8920-401d-ab11-813875c90d50/f036a3d9827afcb8f7437efab69a9dda475c8ead88d0d6dc43ffd3d2c3ac0d69/Microsoft.VC.14.29.16.11.Premium.Tools.HostX86.TargetX86.base.vsix'. One or more errors occurred., Signature: PackageId=Microsoft.VC.14.29.16.11.Premium.Tools.HostX86.TargetX86.base;PackageAction=DownloadPackage;ReturnCode=0x80131500
2022-06-13T23:12:52.2101450Z     vhd: [1b4c:0006][2022-06-13T23:12:42] Error 0x8013153b: Failed install: The operation was canceled.
2022-06-13T23:12:52.2119229Z     vhd:    at Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
2022-06-13T23:12:52.2141916Z     vhd:    at Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
2022-06-13T23:12:52.2154171Z     vhd:
2022-06-13T23:12:52.2173018Z     vhd: Non zero exit code returned by the installation process : 1
2022-06-13T23:12:52.5208568Z ==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present...
2022-06-13T23:12:52.5221680Z ==> vhd: 
2022-06-13T23:12:52.5236943Z ==> vhd: Deleting individual resources ...

### Repro steps

While running the pipeline execution, Package Microsoft.VC.14.29.16.11.Premium.Tools.HostX86.TargetX86.base,version=14.29.30142' failed to download

**Comment by al-cheb** [comment]
Nothing we can help with a flaky network connection.
